### ISSUE TITLE
Agent not submitting data ?

### ISSUE THREAD

**Issue by Patriciawa** [it-novum/openitcockpit-agent#12]
Hi,

I've installed openITCOCKPIT via the apt repository on Debian 10 and all works awesome. However I can't get the agent to submit data correctly. When I go to localhost:3333 I can see the data refresh every thirty seconds but it seems that it won't submit it to openITCOCKPIT, the agent has been installed on Windows 10, latest update with .NET installed. Any help is appreciated. openITCOCKPIT is running the latest version.

Here are some screenshots;

![image](https://user-images.githubusercontent.com/49994443/90225192-313b4680-de11-11ea-9c70-f3ec0b68bda3.png)

![image](https://user-images.githubusercontent.com/49994443/90225218-3bf5db80-de11-11ea-824e-1074ead46176.png)

My config (generated by openITCOCKPIT);

`[default]
address = 0.0.0.0
port = 3333
interval = 30
try-autossl = true
verbose = false
stacktrace = false
config-update-mode = false
auth = 
customchecks = 
temperature-fahrenheit = false
dockerstats = false
qemustats = false
cpustats = true
sensorstats = true
processstats = true
processstats-including-child-ids = false
netstats = true
diskstats = true
netio = true
diskio = true
winservices = true
systemdservices = true
wineventlog = true
alfrescostats = false
alfresco-jmxuser = monitorRole
alfresco-jmxpassword = change_asap
alfresco-jmxaddress = 0.0.0.0
alfresco-jmxport = 50500
alfresco-jmxpath = /alfresco/jmxrmi
alfresco-jmxquery = 
alfresco-javapath = /usr/bin/java

[oitc]
hostuuid = 64f1f526-ad4a-4cc3-8c50-dfa312caa865
url = https://redacted
apikey = redacted
interval = 60
enabled = true

Thanks,

Patrick

**Comment by nook24** [comment]
Is your Agent running in Push or Pull mode?

**Comment by Patriciawa** [comment]
Hi @nook24 ,
The Agent is running in Push mode.

What I noticed is that the time zone of the oitc server was different on the hosts. After I noticed this I changed it back to Berlin.
Then I saw a 404 on the 'Agent Overview' page, I am taking a wild guess here but I think this has to do with the oitc server rather than the agent.

Thanks, 
Patrick

**Comment by nook24** [comment]
Good morning @Patriciawa 
I guess most likely something went wrong with your TLS certificates.

To resolve the issue you should try the following steps:

1. Stop the openITCOCKPIT-Agent on the Windows System using Service Control Manager.
2. Open the openITCOCKPIT Web Interface and navigate to _Agents overview_. Delete the Windows System from `Trunsted Agents` and also delete the Record from `Push cache`
3. Reconfigure the Agent through the Web GUI like so:
![Bildschirmfoto 2020-08-18 um 07 23 57](https://user-images.githubusercontent.com/9019992/90475742-5f2dcd00-e128-11ea-87dd-ac755acfffe6.png)
4. Manually Copy&Paste the shown configuration to `C:\Program Files\it-novum\openitcockpit-agent\config.cnf`
5. Remove all TLS certificate files from `C:\Program Files\it-novum\openitcockpit-agent\`:
![Bildschirmfoto 2020-08-18 um 07 48 40](https://user-images.githubusercontent.com/9019992/90475846-9ac89700-e128-11ea-88d6-88d2b61c7d8f.png)
6. Start the openITCOCKPIT Agent using Service Control Manager.
7. Open _Agents overview_ in openITCOCKPIT Web Interface again and mark the agent as trusted. (Please wait up to 60 seconds so the Agent has some time to send the first request)
![Bildschirmfoto 2020-08-18 um 07 49 26](https://user-images.githubusercontent.com/9019992/90475939-cb103580-e128-11ea-8e42-4c7a83003299.png)

Things should work again as expected.

PS: If TLS got enabled correctly you should not be able to access the Agents API anymore without a valid certificate:
![Bildschirmfoto 2020-08-18 um 07 34 43](https://user-images.githubusercontent.com/9019992/90476259-73be9500-e129-11ea-85f6-5613305d8842.png)

**Comment by Patriciawa** [comment]
Good morning @nook24 

Thanks for your answer, however I can't access the 'Agent Overview' page, it gives a 404.
![image](https://user-images.githubusercontent.com/49994443/90479358-d8302300-e12e-11ea-8186-f06bbdbae82d.png)

**Comment by nook24** [comment]
Strange... There is no 404 exception in the _Agent Overview_. Can you please try if you can query the API directly with your browser like so `https://192.168.56.103/agentconnector/agents.json?angular=true`. Is this also running into a 404 error?

**Comment by Patriciawa** [comment]
@nook24 Jup getting the following:` {"message":"Not Found","url":"\/agentconnector\/agents.json?angular=true","code":404,"_csrfToken":null}`

**Comment by nook24** [comment]
I found the issue. Please copy [this file](https://raw.githubusercontent.com/it-novum/openITCOCKPIT/development/src/Controller/AgentconnectorController.php) to `/opt/openitc/frontend/src/Controller/AgentconnectorController.php` This should resolve the issue. (Or wait for the next Update of openITCOCKPIT)

**Comment by Patriciawa** [comment]
Hi @nook24 

Thanks, I can access the Agents Overview page again. However it doesn't push the records. I can see all the certificates in agent directory plus I can access the web overview from the agent with https://localhost:3333 but getting a timeout, http is not possible anymore.

Thanks for your help!

Patrick

**Comment by Patriciawa** [comment]
What I did noticed in the debug menu is that the `statusngin_cmd` has 480 jobs waiting. Has that something to do with it?

![image](https://user-images.githubusercontent.com/49994443/90751264-2fbcc300-e2d6-11ea-9a81-6b89bd5bf975.png)

**Comment by nook24** [comment]
That's bad new. The `statusngin_cmd` should get processed by the Statusengine Broker and maybe contains the check results from the Agent...

Is your Naemon running `systemctl status naemon`?
Is the right Statusengine Broker loaded in the file `/opt/openitc/nagios/etc/nagios.cfg` ? The last line should be
```
# Broker Options for Statusengine 3 (New C++-Version Statusengine Broker)
broker_module=/opt/openitc/nagios/lib/libstatusengine.so /opt/openitc/etc/statusengine/statusengine.toml
```

You could also try to run the command `openitcockpit-update` to resolve the issue

There was another issue where the `openitcockpit-statusengine3-worker` package was missing in the Debian 10 repository. Maybe you are also affected by this issue: https://github.com/it-novum/openITCOCKPIT/issues/1045#issuecomment-676261278

**Comment by Patriciawa** [comment]
When opening  `/opt/openitc/nagios/etc/nagios.cfg`, it indicates it's running `statusengine2`. When running `openitcockpit-update`, I see that the directory `/opt/openitc/statusenine3` does not exist. How should I install it manually? Running the `upgrade.sh` does not make a difference unfortunately.

**Comment by Patriciawa** [comment]
Fixed it by installing the worker manually. I'll check if the agent is succesfully submitting data.

**Comment by Patriciawa** [comment]
I reinstalled it and it all works fine now. Thanks for your effort.
