### ISSUE TITLE
ARM64 Build of Openitcockpit Agent

### ISSUE THREAD

**Issue by felixrichardt** [it-novum/openitcockpit-agent#51]
This is a (multiple allowed):

* [x ] enhancement
* [x] feature-request

I am running the openITCOCKPIT Agent in:
* [x] Pull Model (openITCOCKPIT Server request data from Agent)
* [ ] Push Model (Agent send data to openITCOCKPIT)

Hi,
is support for arm64 (Debian 10) planned?
Or can we build a deb installer by ourselves?

Greetings

**Comment by nook24** [comment]
Support for ARM64 is planned. Unfortunately we are facing some stability issues with the current version of the Agent on Windows Systems which we are addressing first.

You can also build your own packages: https://github.com/it-novum/openitcockpit-agent#python-3---linux-arm64-on-debian-9

That's how we build the packages:
https://github.com/it-novum/openitcockpit-agent/blob/d6fcff4b296e940ba4b010547146d6a9984c984c/Jenkinsfile#L23-L37

Hope this helps.

**Comment by nook24** [comment]
Today we launched the public beta of the openITCOCKPIT Monitoring Agent 3.0. Please see this blog post for more information:
https://openitcockpit.io/2021/2021/04/14/openitcockpit-monitoring-agent-3-0-public-beta/

It also has builds for arm64 and armhf :)
